# Generated by Django 4.2.13 on 2024-07-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_spouseinfo_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.RemoveField(
            model_name='family',
            name='father',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='spouseinfo',
            name='person',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='SpouseInfo',
        ),
    ]
